name: Release
run-name: Create Automated Semantic Release
on:
  workflow_dispatch:

jobs:
  create-release:
    uses: RhysHoad/terraform-test/.github/workflows/release.yml@v0.0.8
    secrets: inherit
